# Generated by Django 5.0.6 on 2024-08-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcalendarinfo',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionaleventinfo',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='schedule.event'),
        ),
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='scheduler.board'),
        ),
        migrations.AddField(
            model_name='tag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='scheduler.card'),
        ),
        migrations.AddField(
            model_name='task',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduler.card'),
        ),
    ]
