# Build Stage
FROM node:latest AS build

# Set the working directory inside the container
WORKDIR /src

# Copy package.json and package-lock.json from the frontend folder
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy all other source files from the frontend directory
COPY ./frontend .

# Build the Next.js app
RUN npm run build

# Production Stage
FROM node:latest AS production

WORKDIR /src

# Copy the build output from the build stage
COPY --from=build /src/.next ./.next
COPY --from=build /src/node_modules ./node_modules
COPY --from=build /src/public ./public
COPY --from=build /src/package.json ./package.json

# Start the Next.js application
CMD npm start
