# Generated by Django 4.2.15 on 2024-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydevelopment',
            name='project_name',
        ),
        migrations.AddField(
            model_name='communitydevelopment',
            name='community',
            field=models.CharField(blank=True, choices=[('RURAL', 'Rural'), ('URBAN', 'Urban'), ('INDIGENOUS', 'Indigenous')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='educational_needs',
            field=models.CharField(blank=True, choices=[('BOOKS', 'Books'), ('SCHOLARSHIP', 'Scholarship'), ('INFRASTRUCTURE', 'Infrastructure')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrelief',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrelief',
            name='relief_timeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentalprotection',
            name='environmental_goals',
            field=models.CharField(blank=True, choices=[('PLANTING TREES', 'Planting Trees'), ('REDUCING POLLUTION', 'Reducing Pollution')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcareinstitution',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('CANCER', 'Cancer'), ('DIABETES', 'Diabetes'), ('GENERAL_HEALTH_SUPPORT', 'General Health Support')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthcareinstitution',
            name='number_of_patients_benefiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthcarepatient',
            name='number_of_patients_benefiting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalprotection',
            name='conservation_type',
            field=models.CharField(choices=[('REFORESTATION', 'Reforestation'), ('WEILDLIFE PROTECTION', 'Wildlife Protection'), ('CLEAN WATERS', 'Clean Waters')], max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcareinstitution',
            name='institution_type',
            field=models.CharField(choices=[('HOSPITAL EQUIPMNET', 'Hospital Equipment'), ('PATIENT CARE', 'Patient Care'), ('HEALTH CENTER', 'Health Center'), ('SENIOR HOMES', 'Senior Homes'), ('MEDICAL SUPPLIES', 'Medical Supplies')], max_length=50),
        ),
    ]
