# Generated by Django 5.0.6 on 2024-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='email',
            new_name='institution_email',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='name',
            new_name='institution_name',
        ),
    ]
