# Generated by Django 5.0.6 on 2024-08-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionadmin',
            old_name='institution_id',
            new_name='institution',
        ),
    ]
