# Generated by Django 5.0.6 on 2024-08-15 12:08

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Contact Person email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Institution Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.Institution.user_directory_path, verbose_name='Institution Certificate'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_license',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.Institution.user_directory_path, verbose_name='Institution License'),
        ),
    ]
