# Generated by Django 5.0.6 on 2024-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('bsystems_admin', 'Bsystems Admin'), ('institution_admin', 'Institution Admin'), ('user', 'User')], default='user', max_length=50, null=True, verbose_name='Roles'),
        ),
    ]
