# Generated by Django 5.0.6 on 2024-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('bsystems_admin', 'Bsystems Admin'), ('institution_admin', 'Institution Admin'), ('user', 'User')], default='user', max_length=50, verbose_name='Roles'),
        ),
    ]
