# Generated by Django 4.2.15 on 2024-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Password Confirmation'),
        ),
    ]
