<<<<<<< HEAD
# Generated by Django 4.2.15 on 2024-09-13 09:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
=======
# Generated by Django 5.0.6 on 2024-09-12 21:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models
>>>>>>> 9ec0c839d6911661761166fbd57e26543d4dbfa1


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Company')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Address')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company District')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Region')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 9ec0c839d6911661761166fbd57e26543d4dbfa1
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('beneficiary_type', models.CharField(blank=True, choices=[('EDUCATIONAL_INSTITUTION', 'Educational Institution'), ('HEALTHCARE_INSTITUTION', 'Healthcare Institution'), ('HEALTHCARE_PATIENT', 'Healthcare Patient'), ('ANIMAL', 'Animal'), ('SOCIAL_WELFARE_PROGRAM', 'Social Welfare Program'), ('EMERGENCY_RELIEF', 'Emergency Relief'), ('ENVIRONMENTAL_PROTECTION', 'Environmental Protection/Conservation'), ('COMMUNITY_DEVELOPMENT', 'Community Development'), ('DISABILITY_SUPPORT', 'Disability Support')], max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('associated_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='users.institution')),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Company')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Address')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company District')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Region')),
=======
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_analytics.company')),
>>>>>>> 9ec0c839d6911661761166fbd57e26543d4dbfa1
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('primary_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='contact_analytics.accountprofile')),
            ],
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='accountprofile',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_analytics.company'),
        ),
=======
>>>>>>> 9ec0c839d6911661761166fbd57e26543d4dbfa1
    ]
