<<<<<<< HEAD
# Generated by Django 4.2.15 on 2024-09-13 16:11
=======
# Generated by Django 4.2.15 on 2024-10-07 10:19
>>>>>>> 1b373edb531ba54d5c80232568ae6c422c783b9f

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('users', '0001_initial'),
>>>>>>> 1b373edb531ba54d5c80232568ae6c422c783b9f
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('beneficiary_type', models.CharField(blank=True, choices=[('EDUCATIONAL_INSTITUTION', 'Educational Institution'), ('HEALTHCARE_INSTITUTION', 'Healthcare Institution'), ('HEALTHCARE_PATIENT', 'Healthcare Patient'), ('ANIMAL', 'Animal'), ('SOCIAL_WELFARE_PROGRAM', 'Social Welfare Program'), ('EMERGENCY_RELIEF', 'Emergency Relief'), ('ENVIRONMENTAL_PROTECTION', 'Environmental Protection/Conservation'), ('COMMUNITY_DEVELOPMENT', 'Community Development'), ('DISABILITY_SUPPORT', 'Disability Support')], max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Company')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Address')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company District')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Region')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('primary_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='contact_analytics.accountprofile')),
            ],
        ),
    ]
