# Generated by Django 5.0.6 on 2024-08-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='associated_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='users.institution'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_analytics.company'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='contact_analytics.accountprofile'),
        ),
    ]
